### ISSUE TITLE
Complete re-write of web-app's front-end

### ISSUE THREAD

**Issue by devkhan** [draeger-lab/EscherConverter#24]
The not-at-all good looking client-side of the web-app needs to be written properly. Initially it was written quickly without caring about design, best practices, or maintenance. And I must be blamed for that.

Important points to consider:
- Using a data-binding library like [Rivets](//rivetsjs.com) instead of DOM manipulation (which will(has) inherently lead to callback mess).
- The current CSS library [Picnic](//picnicss.com) is fine, but it can be changed. It just needs to be lightweight.
- The most important thing to remember is to keep it light (it weighs ~40 KB right now).

**Comment by Saurabh3012** [comment]
I can do that for you

**Comment by draeger** [comment]
Hi @Saurabh3012, thanks for your interest! We should get in touch and make a plan how to coordinate this effort.

**Comment by devkhan** [comment]
Awesome. I'll write a `CONTRIBUTING` guide in a couple of days so that you easily setup the development environment. You can also personally contact me if you want.

**Comment by Saurabh3012** [comment]
Thanks a lot for your replies. Looking forward to start contributing. Just
let me when and how I can do so.

**Comment by draeger** [comment]
We could do an open Google Hangout meeting and discuss in person. How about Tuesday, Oct 25th between 10 and 12 a.m. CET?

**Comment by devkhan** [comment]
@draeger Actually, @Saurabh3012 and I study in the same institute, so I'll just have a talk with him and let you know.

**Comment by draeger** [comment]
Sounds good!

**Comment by zakandrewking** [comment]
question: will this interface live separately from [ZBIT](https://webservices.cs.uni-tuebingen.de/)? I will we continue developing on that?

seems like overkill to have 2 separate web-based conversion interfaces

**Comment by zakandrewking** [comment]
also, thanks for your interest @Saurabh3012! It's great to have new collaborators!
