### ISSUE TITLE
Going the reverse direction: from standard format to Escher map

### ISSUE THREAD

**Issue by Midnighter** [draeger-lab/EscherConverter#32]
Just a simple question, are there or do you have plans for tools that can take a model with coordinates and produce an Escher map? Thank you for illuminating me.

**Comment by draeger** [comment]
Thanks for this request. Converting from SBGN-ML or SBML+Layout to Escher's JSON is definitely doable and should be straightforward to achieve. Is this a feature you need for your ongoing work? If so, we can add it as a feature request to our TODO list.

**Comment by Midnighter** [comment]
I was thinking back to the existing maps for the yeast-GEM in cell designer and I was wondering if getting them into Escher is a tooling issue or the lack of a clear tutorial/documentation. Sounds like it's the latter.
